<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedListingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('listings')->delete();
        
        \DB::table('listings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 2,
                'package_id' => 1,
                'image' => '/uploads/media_image_6593014af1ac9.jpg',
                'thumbnail' => '/uploads/media_thumbnail_6593014af28b3.jpg',
                'title' => 'Romantic Boat Trip',
                'seo_title' => 'Romantic Boat Trip',
                'slug' => 'romantic-boat-trip',
            'description' => '<p><span style="color: rgb(124, 116, 116); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 15px;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur.',
                'phone' => '01011157600',
                'email' => 'example@gmail.com',
                'address' => 'Washington, Indiana',
                'website' => 'https://example.com',
                'facebook_link' => 'https://example.com',
                'twitter_link' => 'https://example.com',
                'linkedin_link' => 'https://example.com',
                'whatsapp_link' => 'https://example.com',
                'is_verified' => 0,
                'is_featured' => 0,
                'views' => 0,
                'google_map_embed_code' => NULL,
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 18:15:38',
                'updated_at' => '2024-01-01 18:15:38',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'category_id' => 2,
                'location_id' => 1,
                'package_id' => 1,
                'image' => '/uploads/media_image_659302555f42d.jpg',
                'thumbnail' => '/uploads/media_thumbnail_65930255602ff.jpg',
                'title' => 'Et harum error repud',
                'seo_title' => 'Vel dolores deserunt',
                'slug' => 'et-harum-error-repud',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span></p>',
                'seo_description' => 'Quaerat rerum nostru',
            'phone' => '+1 (162) 964-6745',
                'email' => 'fynyjahyn@mailinator.com',
                'address' => 'Libero et qui perspi',
                'website' => 'https://www.xugubefi.co',
                'facebook_link' => 'https://www.xugubefi.co',
                'twitter_link' => 'https://www.xugubefi.co',
                'linkedin_link' => 'https://www.xugubefi.co',
                'whatsapp_link' => 'https://www.xugubefi.co',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Quisquam quis ipsa',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 18:20:05',
                'updated_at' => '2024-01-01 18:20:05',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_65931134ddd05.jpg',
                'thumbnail' => '/uploads/media_thumbnail_65931134de7bf.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:23:32',
                'updated_at' => '2024-01-01 19:23:32',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_659311cb63308.jpg',
                'thumbnail' => '/uploads/media_thumbnail_659311cb63cf7.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:26:03',
                'updated_at' => '2024-01-01 19:26:03',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_6593125b7ca15.jpg',
                'thumbnail' => '/uploads/media_thumbnail_6593125b7d40c.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:28:27',
                'updated_at' => '2024-01-01 19:28:27',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_659312b274932.jpg',
                'thumbnail' => '/uploads/media_thumbnail_659312b2753cf.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:29:54',
                'updated_at' => '2024-01-01 19:29:54',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_659312cd96401.jpg',
                'thumbnail' => '/uploads/media_thumbnail_659312cd97d97.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:30:21',
                'updated_at' => '2024-01-01 19:30:21',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_6593137c7b68f.jpg',
                'thumbnail' => '/uploads/media_thumbnail_6593137c7c3e8.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:33:16',
                'updated_at' => '2024-01-01 19:33:16',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_659313b9aa36b.jpg',
                'thumbnail' => '/uploads/media_thumbnail_659313b9ab17f.jpg',
                'title' => 'Labore voluptas pers',
                'seo_title' => 'Illum in et et minu',
                'slug' => 'labore-voluptas-pers',
            'description' => '<p><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus.</span><span style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; color: rgb(124, 116, 116); display: block; font-family: &quot;Nunito Sans&quot;, sans-serif;">Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant.</span></p>',
                'seo_description' => 'Perferendis non odio',
            'phone' => '+1 (501) 792-7239',
                'email' => 'hofaj@mailinator.com',
                'address' => 'Fugiat explicabo M',
                'website' => 'https://www.zakacybebejogoc.info',
                'facebook_link' => 'https://www.zakacybebejogoc.info',
                'twitter_link' => 'https://www.zakacybebejogoc.info',
                'linkedin_link' => 'https://www.zakacybebejogoc.info',
                'whatsapp_link' => 'https://www.zakacybebejogoc.info',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Enim ut eu cupidatat',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:34:17',
                'updated_at' => '2024-01-01 19:34:17',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'category_id' => 2,
                'location_id' => 3,
                'package_id' => 1,
                'image' => '/uploads/media_image_6593143a3a10a.png',
                'thumbnail' => '/uploads/media_thumbnail_6593143a3ab7d.jpg',
                'title' => 'Asperiores mollit eo',
                'seo_title' => 'Nulla assumenda sint',
                'slug' => 'asperiores-mollit-eo',
            'description' => '<h2 style="border-width: 0px; border-style: solid; border-color: rgb(226, 232, 240); --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-size: 1.8em; margin-right: 0px; margin-bottom: 0.888889em; margin-left: 0px; line-height: 1.11111; font-family: &quot;Albert Sans&quot;;">Real-life example of pivot tables</h2><p><span style="color: rgb(55, 65, 81); font-family: &quot;Albert Sans&quot;; font-size: 20px;">In official documentation they show the example of User-Role relationships, where user potentially can belong to several roles, and vice versa. So to make things clearer - let\'s take another real-life example:&nbsp;</span><span style="border-width: 0px; border-style: solid; border-color: rgb(226, 232, 240); --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-weight: bolder; margin-top: 0px; color: rgb(55, 65, 81); font-family: &quot;Albert Sans&quot;; font-size: 20px;">Shops</span><span style="color: rgb(55, 65, 81); font-family: &quot;Albert Sans&quot;; font-size: 20px;">&nbsp;and&nbsp;</span><span style="border-width: 0px; border-style: solid; border-color: rgb(226, 232, 240); --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-weight: bolder; color: rgb(55, 65, 81); font-family: &quot;Albert Sans&quot;; font-size: 20px;">Products</span><span style="color: rgb(55, 65, 81); font-family: &quot;Albert Sans&quot;; font-size: 20px;">. Let\'s say a company has a dozen of Shops all over city/country and a variety of products, and they want to store the information about which Product is sold in which Shop. It\'s a perfect example of many-to-many relationship: one product can belong to several shops, and one shop can have multiple products.</span><br></p>',
                'seo_description' => 'Corporis consequuntu',
            'phone' => '+1 (129) 331-2748',
                'email' => 'saropi@mailinator.com',
                'address' => 'Nulla enim facilis v',
                'website' => 'https://www.sejufuzo.in',
                'facebook_link' => 'https://www.sejufuzo.in',
                'twitter_link' => 'https://www.sejufuzo.in',
                'linkedin_link' => 'https://www.sejufuzo.in',
                'whatsapp_link' => 'https://www.sejufuzo.in',
                'is_verified' => 1,
                'is_featured' => 1,
                'views' => 0,
                'google_map_embed_code' => 'Hic ullamco quia vol',
                'attachement' => NULL,
                'status' => 1,
                'expire_at' => '2024-03-01',
                'deleted_at' => NULL,
                'created_at' => '2024-01-01 19:36:26',
                'updated_at' => '2024-01-01 19:36:26',
            ),
        ));
        
        
    }
}